CREATE FUNCTION FN_TOKEN_VALIDO
(
    @TOKEN NVARCHAR(MAX)
)
RETURNS INT
AS 
BEGIN

DECLARE @USUARIO_ID INT = 0

SELECT
    @USUARIO_ID = A.USUARIO_ID
FROM USUARIOS_TOKENS A WITH(NOLOCK)
WHERE A.TOKEN = @TOKEN
AND A.DATA_EXPIRACAO >= GETDATE()

RETURN @USUARIO_ID

END