CREATE PROCEDURE SP_ATUALIZAR_PRODUTO
(
    @PRODUTO_ID INT,
    @NOME VARCHAR(255),
	@SLUG VARCHAR(255),
	@DESCRICAO VARCHAR(500),
	@PRECO NUMERIC(15,4),
	@ESTOQUE NUMERIC(15,4),
	@ATIVO BIT,
	@USUARIO_ALTERACAO INT
)
AS
BEGIN

    UPDATE A
    SET
    NOME = @NOME,
    SLUG = @SLUG,
    DESCRICAO = @DESCRICAO,
    PRECO = @PRECO,
    ESTOQUE = @ESTOQUE,
    ATIVO = @ATIVO,
    USUARIO_ALTERACAO = @USUARIO_ALTERACAO
    FROM PRODUTOS A WITH(NOLOCK)
    WHERE A.ID = @PRODUTO_ID
END