ALTER PROCEDURE SP_LISTAR_PRODUTOS
(
    @SLUG VARCHAR(255),
    @NOME VARCHAR(255),
    @PRECO NUMERIC(15,4),
    @ESTOQUE NUMERIC(15,4),
    @ATIVO BIT
)
AS
BEGIN
    SELECT
        A.ID,
        A.NOME,
        A.SLUG,
        A.DESCRICAO,
        A.PRECO,
        A.ESTOQUE,
        A.ATIVO,
        B.USUARIO AS USUARIO_INCLUSAO,
        C.USUARIO AS USUARIO_ALTERACAO
    FROM PRODUTOS A WITH(NOLOCK)
    JOIN USUARIOS B WITH(NOLOCK) ON B.ID = A.USUARIO_INCLUSAO
    LEFT JOIN USUARIOS C WITH(NOLOCK) ON C.ID = A.USUARIO_ALTERACAO
    WHERE (A.SLUG = @SLUG OR ISNULL(@SLUG, '') = '')
    AND (A.NOME = @NOME OR ISNULL(@NOME, '') = '')
    AND (A.PRECO = @PRECO OR ISNULL(@PRECO, 0) = 0) 
    AND (A.ESTOQUE = @ESTOQUE OR ISNULL(@ESTOQUE, 0) = 0)
    AND (A.ATIVO = @ATIVO OR ISNULL(@ATIVO, 0) = 0)
END