CREATE PROCEDURE SP_LOGAR_USUARIO
(
    @USUARIO VARCHAR(30),
    @SENHA VARCHAR(255)
)
AS
BEGIN
SET NOCOUNT ON;

DECLARE @ID INT

SELECT @ID = A.ID
FROM USUARIOS A WITH(NOLOCK)
WHERE A.USUARIO = @USUARIO
AND A.SENHA = @SENHA

IF @ID IS NULL
BEGIN

    SELECT
        0 AS LOGOU,
        '' AS TOKEN,
        'Não foi possivel localizar usuário informado!' AS MENSAGEM
    
    RETURN
END
ELSE
BEGIN
    DECLARE @TOKEN NVARCHAR(MAX)
    SET @Token = CONVERT(NVARCHAR(50), HASHBYTES('SHA2_256', CAST(NEWID() AS NVARCHAR(36)) + CAST(@ID AS NVARCHAR(10))), 2)

    INSERT INTO USUARIOS_TOKENS (USUARIO_ID, TOKEN)
    VALUES (@ID, @TOKEN)


        SELECT
            1 AS LOGOU,
            @TOKEN AS TOKEN,
            'Logado com sucesso!' AS MENSAGEM
        
    END
END
