CREATE TABLE USUARIOS
(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	USUARIO VARCHAR(30) NOT NULL UNIQUE,
	SENHA VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE PRODUTOS
(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	SLUG VARCHAR(255) NOT NULL UNIQUE,
	DESCRICAO VARCHAR(500) NULL,
	PRECO NUMERIC(15,4) NOT NULL,
	ESTOQUE NUMERIC(15,4) NOT NULL DEFAULT 0,
	ATIVO BIT,
	USUARIO_INCLUSAO INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID),
	USUARIO_ALTERACAO INT NULL FOREIGN KEY REFERENCES USUARIOS(ID)
);

CREATE TABLE USUARIOS_TOKENS
(
	ID INT PRIMARY KEY IDENTITY,
	USUARIO_ID INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID),
	TOKEN NVARCHAR(MAX),
	DATA_CRIACAO DATETIME DEFAULT GETDATE(),
	DATA_EXPIRACAO DATETIME DEFAULT DATEADD(HOUR, 8, GETDATE())
);

CREATE TABLE PRODUTOS_LOG
(
	ID INT PRIMARY KEY IDENTITY,
	PRODUTO_ID INT NOT NULL,
	TIPO VARCHAR(1) NOT NULL,
	DATA_LOG DATETIME NOT NULL DEFAULT GETDATE(),
	COUNTEUDO_ANTERIOR XML NULL,
	COUNTEUDO_ATUAL XML NULL
);