CREATE TRIGGER TR_GERAR_LOG_PRODUTOS
ON PRODUTOS
AFTER DELETE, UPDATE
AS
BEGIN

    SET NOCOUNT ON;

    INSERT INTO PRODUTOS_LOG(PRODUTO_ID, TIPO)
    SELECT
        D.ID,
        'D'
    FROM DELETED D
    LEFT JOIN INSERTED I ON I.ID = D.ID
    WHERE I.ID IS NULL;

    
    INSERT INTO PRODUTOS_LOG(PRODUTO_ID, TIPO, COUNTEUDO_ANTERIOR, COUNTEUDO_ATUAL)
    SELECT
        D.ID,
        'U',
        (SELECT D.* FOR XML PATH('Produto'), ROOT('Anterior')) AS COUNTEUDO_ANTERIOR,
        (SELECT I.* FOR XML PATH('Produto'), ROOT('Atual')) AS COUNTEUDO_ATUAL
    FROM INSERTED I
    INNER JOIN DELETED D ON D.ID = I.ID;

END